[GLOBAL]
pants_version = "2.12.0"

backend_packages.add = [
  "pants.backend.docker",
  "pants.backend.python",
  "pants.backend.codegen.protobuf.python",
]

[python]
enable_resolves = false
interpreter_constraints = ["CPython==3.8.*"]

[python-repos]
repos = ["%(buildroot)s/thirdparty/python/wheels/"]

[python.resolves]
python-default = "thirdparty/python_default_lockfile.txt"

[source]
root_patterns = ["src/python"]


[anonymous-telemetry]
enabled = false
