[GLOBAL]
pants_version = "2.10.0"
use_deprecated_python_macros = false

backend_packages.add = [
  "pants.backend.docker",
  "pants.backend.python",
  "pants.backend.python.typecheck.mypy"
]

[python]
enable_resolves = true
interpreter_constraints = ["CPython==3.8.*"]

[python.resolves]
python-default = "thirdparty/python_default_lockfile.txt"

[source]
root_patterns = ["src/python"]


[anonymous-telemetry]
enabled = false